[[organizations]]
logo = "coderefinery.png"
text = """
[CodeRefinery](https://coderefinery.org) offers training opportunities to
researchers from Nordic research groups and projects to learn basic-to-advanced
research computing skills and become confident in using state-of-the-art tools
and practices from modern collaborative software engineering.
"""

[[organizations]]
logo = "eScience_logo.png"
text = """
The [Netherlands eScience Center](https://www.esciencecenter.nl/) is the Dutch national hub for expertise in e-infrastructure (optimized data handling, big data analytics and efficient computing), promoting software sustainability, reuse, collaboration and preventing “reinventing the wheel”."""

[[organizations]]
logo = "dlr_logo.png"
text = """
The [German Aerospace Center (DLR)](https://dlr.de/EN/) is the Federal Republic of Germany's research centre for aeronautics and space. We conduct research and development activities in the fields of aeronautics, space, energy, transport, security and digitalisation."""

[[organizations]]
logo = "gfz_logo.png"
text = """
The [GFZ](https://www.gfz-potsdam.de/) German Research Centre for Geosciences is the national research centre for Earth sciences in Germany. """

[[organizations]]
logo = "ssi_logo.png"
text = """
The [Software Sustainability Institute (SSI)](https://www.software.ac.uk/) is a national facility for better research software, based in the UK. Since 2010, the Software Sustainability Institute has facilitated the advancement of software in research by cultivating better, more sustainable, research software to enable world-class research (“Better software, better research”). 
"""


# other organizations can be added like this:
#[[organizations]]
#logo = "mylogo.png"
#text = """
#Some short text about this organization in Markdown"
#"""
